cognitedata/seismic-proto

- Jenkinsfile
This build doesnt need a node with local ssd. This mighjt slow down the build.
> Remove nodeselector

- cognite/seismic/protos/ingest_service.proto
- cognite/seismic/protos/ingest_service_messages.proto
- cognite/seismic/protos/query_service.proto
- cognite/seismic/protos/query_service_messages.proto
- cognite/seismic/protos/types.proto
Endpoints added are:
- list/add/remove projects that hava access to files (only allowed to the owner project)
- list files - will list all files a project has access to. This is different from list surveys, which will list surveys and files it owns for compatibility reasons. List surveys behaviour may be changed in he future for consistency or it can be removed and replaced by list files after agreement with current users
> Adds endpoints for cross-project file sharing

- cognite/seismic/protos/v1/seismic_service.proto
- cognite/seismic/protos/v1/seismic_service_datatypes.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
Adds search endpoint to v1, because they currently only exist for v0 in the form of "get" and "list". The return type File is already thin, with only metadata, name, id, extid, so no modifications are needed.
> Feat: Add Search Files endpoint to v1

- cognite/seismic/protos/query_service_messages.proto
- cognite/seismic/protos/types.proto
That way callers can reset surveys back to the old behavior of deducing.
> Explicity DeduceFromTraces field in SurveyGridTransformation

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
I didn't realize that Survey was duplicated in v1.
Also redefined fields in v1's `CreateSurveyRequest` and `EditSurveyRequest` to take crs as string instead of the CRS type, to be consistent with the rest of the v1 API. These endpoints are unimplemented, so it should be fine, right?
> Return SurveyGridTransformation to users in v1 too

- cognite/seismic/protos/query_service_messages.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
Unfortunate naming - better fix earlier than later. Proto tags are unchanged, so wire format is compatible. It'll break implementations when merged, though.
> Rename Horizon to Surface

- cognite/seismic/protos/v1/seismic_service_messages.proto
Add force option that creates a seismic even if the intersection is empty (contains no traces).
> Feat: Add force option to CreateSeismicRequest

- .github/workflows/build-docs.yml
- .github/workflows/validate-proto.yml
- build-docs.sh
- cognite/seismic/protos/v1/seismic_service.proto
- markdown_preamble.md
This moves the invocations of protoc-gen-doc into a shell script to give us a bit more room for evil hackery.
We now build separate files for v0 and v1 APIs, one page for both v0 and v1 APIs, and finally one with all the proto files, like we have done previously. This latter variant should probably go away, as there are proto files in this repository that are not part of the API as such.
Finally we include a preamble in the Markdown files to get a sidebar when they're converted to HTML for the docs site later.
> SBS-3771 Build more docs bettererer

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
On very large datasets, the embedded seismics exceeded the max message size (10MB) for partitions. So we will remove the embedded seismics and instead return a list of IDs. Seismics can instead be retrieved using the "by partition" method.
> Remove seismics from partition

- cognite/seismic/protos/query_service_messages.proto
- cognite/seismic/protos/v1/seismic_service_datatypes.proto
If we deprecate BinaryHeader.file_id and TextHeader.file_id, we can
remove all uses of the corresponding database columns, and remove them.
> Deprecate header file_ids

- cognite/seismic/protos/v1/seismic_service_messages.proto
Deprecating the old `CoverageParameters`.
> V1 SearchSurveysRequest: Add CoverageSpec param

- cognite/seismic/protos/v1/seismic_service_messages.proto
Currently trying to search for "failed jobs", for example, returns a ton of jobs which can be a bit overwhelming when you might only want the ones from the last 2 days. Supporting at most one of each filter seems reasonable.
> V1 Search jobs - Multiple filters

- cognite/seismic/protos/v1/seismic_service.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
When supporting geometry queries in the V1 API, we'll want to compute
the total size of returned traces (for `volume_seismic.get_volume_size`)
as well as the min, max, step encompassing all inlines and xlines (for
finding proper array sizes in `volume_seismic.get_array`). This is
doable from just the volume def with line-based queries, but not with
spatial queries. So instead of adding more and more code duplication to
the sdk, perform the computation on the server side with a new rpc.
> Add a GetVolumeBounds rpc for estimating size

- cognite/seismic/protos/v1/seismic_service_messages.proto
Turns out we need an explicit sample_count field. I had thought that
could be found from bounds.z, but bounds is not always present. So give
the explicit sample count as well.
> VolumeBoundsResponse: Add sample_count

- cognite/seismic/protos/ingest_service_messages.proto
- cognite/seismic/protos/types.proto
- cognite/seismic/protos/v1/seismic_service.proto
- cognite/seismic/protos/v1/seismic_service_datatypes.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
During file registration, convey which header fields should be used for indexing and their respective offsets
Using the wording "POSTSTACK_2D_SHOTPOINT" to avoid confusion with "ENERGY_SOURCE_POINT"
According to PGS, offset 17 (energy source point) is always present, therefore we are adding support for that field.
> Convey 2D offsets and trace headers in file registration

- cognite/seismic/protos/types.proto
- cognite/seismic/protos/v1/seismic_service_datatypes.proto
@audunska 's comment on moving v1 data types to the v1 package wasn't addressed in the last PR
> Move v1 data types

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
Since `dimensions` is also editable, it would make sense to returned it in the `SourceSegyFile` message
Also, keep a consistent naming of the fields between the request message and the response message
> Return all editable fields

- cognite/seismic/protos/v1/seismic_service.proto
- cognite/seismic/protos/v1/seismic_service_datatypes.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
Mainly to support `id_int` in the request, as that's the id our users will be carrying around
> Bring the ingest API to the V1 api

- cognite/seismic/protos/v1/seismic_service_messages.proto
Adding the new extent/geometry types to the existing SegYSeismicRequest. My thinking was we can convert a `query` into a `filter` until we decide to remove it, and the 0.3 sdk only has to deal with `filter`. Or we could have an entirely new message/rpc, I'm happy with either approach really.
> GetSegYFile - 2d support

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
Return the trace header fields and dimensionality that the seismic store was created/updated with from the source segy file. For seismics we can just copy the trace header fields and dimensionality from the seismic store model
> Return header-fields/dimension in seismic/store

- cognite/seismic/protos/v1/seismic_service_messages.proto
in a separate argument. If not given, default to Cdp or Inline/Crossline.
Alternative to #187
> Specify trace key header in addition to `include_extent`

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
to indicate that the seismic was created with `volume = null`, so it
inherits its extents from the seismicstore.
We won't be able to return this variant for 3D seismics, because there is no way to distinguish those seismics that were created before we started recording the source cutouts, from those that were created with `volume = null`. But we can do it for 2d cutouts.
What should we do with the 3d cutouts?
> SeismicCutout: Add `full` variant

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
Fun fact: This change automatically also gives an API for searching for other objects (seismicstores, seismics) by geometry. But that's for later.
> Support survey search by geometry

- cognite/seismic/protos/v1/seismic_service.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
Some failed ingestion results are really hard to debug. It can help to
get a look at what the ingestion worker has seen so far before failing,
such as trace extents. Here is a suggested endpoint to peek at the
unpublished seismicstore resulting from a failed ingestion, in order to
debug.
Alternatively, we could add `allow_unpublished` to
`SearchSeismicStoresRequest`, but keeping it as a separate endpoint
which is explicitly meant for debugging seems to more clearly
communicate the debugging intent.
Are there any potential consistency problems with allowing data managers
to see unpublished seismic stores like this?
Also, naming is hard. Alternatives welcome.
> Add endpoint to debug ingestion

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
~~I changed the names from the ticket:~~
* ~~CDP_TRACE -> TRACE_NUMBER_WITHIN_ENSEMBLE~~
* ~~OFFSET -> DISTANCE_FROM_SOURCE~~
~~I did this because I think it's better to err on the side of verbosity for fields that don't necessarily have a standard name. I personally wasn't sure what CDP_TRACE/CDP difference was at first glance, and OFFSET could've been anything (byte offset?). Opinions welcome.~~
They are fairly industry standard names, we are stickign with them it seems...
Similar PRs for schema and service to follow.
> [SEIS-1173] Prestack: Add trace header fields.

- cognite/seismic/protos/v1/seismic_service_messages.proto
for resumable grpc downloads. Suggestions for different naming is welcome.
We might also want to add a field to identify the revision. Something like an etag, (which would need to be included in one of the `SegYSeismicResponse`s?) or a `last_updated` date.
> Add skip_messages field to SegYSeismicRequest

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
- cognite/seismic/protos/v1/seismic_service_messages.proto
Right now I've added it as, essentially, an AND clause to every search.
If we think there isn't a use case for filter specificity, it would be simpler to only allow searching by one of (identifier, last_modified). Opinions would be appreciated
> Add last_modified to v1 search endpoints

- cognite/seismic/protos/v1/seismic_service_datatypes.proto
Really just a doc update.
To be merged after the 0.3 release.
> Deprecate Seismic LineRange field
