cognite/seismic/protos/query_service.proto

https://cognitedata.atlassian.net/secure/RapidBoard.jspa?rapidView=130&projectKey=SBS&modal=detail&selectedIssue=SBS-953

Remove unimplemented endpoints

---

cognite/seismic/protos/v1/seismic_service_messages.proto

Let's handle this change in the service and then merge it back.

Revert "Fix: Make name optional & add metadata to seismicstore"

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

This reverts commit 40dd87d43aab371e65387f10c60f980b0ff1e1ad.
I want to point seismic-resource/master to this commit without failing compilation. Currently it's pointing to a commit that isn't attached to any branch

Revert "SBS-1323 - Add volume_defs to SeismicStore type (#82)"

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

Apply after #89 for volume_def changes in seismic-resource branch

Now add volume def back

---

cognite/seismic/protos/v1/seismic_service_messages.proto

Fix: GetVolume's seismic store id is int

---

cognite/seismic/protos/types.proto

SBS-2367 Trace index offsets

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

More ids that need to be integers

Fix: Seismic seismicstore_id and partition_id are int

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

seismic-resource/master is already using these commits

Merge sky/yet-another-id-int

---

cognite/seismic/protos/query_service_messages.proto
cognite/seismic/protos/types.proto
cognite/seismic/protos/v1/seismic_service.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

Main pr: https://github.com/cognitedata/seismic-resource/pull/321

SBS-2703 GetSegYFile Proto

---

CODEOWNERS
README.MD
cognite/seismic/protos/ingest_job.proto
cognite/seismic/protos/ingest_service_messages.proto
cognite/seismic/protos/v1/seismic_service_datatypes.proto

This is the bare minimum of interface/message changes for having multiple storage tiers

Multi-tiered protobuf changes

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

Add geojson flag to support retrieving by geojson
https://github.com/cognitedata/seismic-resource/pull/493
https://github.com/cognitedata/seismic-proto/pull/108
https://github.com/cognitedata/cognite-seismic-sdk/pull/267

[SBS-3036] Add geojson flag

---

cognite/seismic/protos/ingest_service_messages.proto
cognite/seismic/protos/types.proto
cognite/seismic/protos/v1/seismic_service_datatypes.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

Question: Should we bump the iteration? Doesn't seem like this has happened too much...

Specify the grid transformation in surveys

---

cognite/seismic/protos/ingest_service_messages.proto
cognite/seismic/protos/query_service_messages.proto
cognite/seismic/protos/types.proto
cognite/seismic/protos/v1/seismic_service_datatypes.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

SBS-3638: Add customer-specified survey coverage

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

I would like to add the URL as a link in VolumeDef schema, but not sure if I succeed or not.

Adding more details for VolumeDef

---

.github/workflows/build-docs.yml

This should do it.
See:
https://github.com/pseudomuto/protoc-gen-doc

Build markdown docs

---

.github/workflows/build-docs.yml

This should fix the 404 on https://cognitedata.github.io/seismic-proto/

Build both HTML and markdown docs.

---

cognite/seismic/protos/types.proto

Add the concept of a CRS, inline and xline.

adding general definitions

---

cognite/seismic/protos/v1/seismic_service_messages.proto

Should be compared with @audunska pr when reviewing. The main difference is the use of a enum for the volume filters.

SBS-3213 V1 geometry - alternative

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

Will only implement for surveys, for now.

Feat: Add metadata filter

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

Trace count and created_empty status

Seismic trace count

---

cognite/seismic/protos/v1/seismic_service_messages.proto

The master branch proto is inaccurate to the version that is currently being used.

Fix: EditSurvey, Use stringvalue for crs

---

cognite/seismic/protos/ingest_service_messages.proto
cognite/seismic/protos/types.proto

Extend the proto to allow passing the dimensionality when registering a file

Add dimensionality

---

cognite/seismic/protos/v1/seismic_service.proto
cognite/seismic/protos/v1/seismic_service_datatypes.proto

Added CloudStorageFile that incorporates some of the comments @amorken left on the V1 Files PR.
This work is related to [SEIS-417](https://cognitedata.atlassian.net/browse/SEIS-417). 
The plan is to implement this chunk first to enable SEIS-417.

Add a SourceSegyFile, return that from SearchFiles

---

cognite/seismic/protos/types.proto

Probably useful for people consuming the traces!

Add 2d headers to Trace proto

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

[SEIS-1083]
[SEIS-1083]: https://cognitedata.atlassian.net/browse/SEIS-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `crs` field to `SourceSegYFile`

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

CRS in seismicstore and survey_id in SourceSegyFile

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

SeismicStore: Include integer survey id

---

Migration.md

Haven't tested examples yet. What I wrote is what makes sense to me based on the documentation.
Will try to test the examples and see if they make sense, they work, and they return what they promise to return.

Add migration

---

cognite/seismic/protos/v1/seismic_service_datatypes.proto

The service returns cloud storage path with the file name included. Update the protobuf comment to reflect that.

Update SourceSegyFile cloud_storage_path

---

cognite/seismic/protos/types.proto
cognite/seismic/protos/v1/seismic_service_datatypes.proto
cognite/seismic/protos/v1/seismic_service_messages.proto

Necessary api changes for pre-stack. Based on #217.

Pre-stack API changes
